export const services = {
    meta: { title: "Services", description: "Product strategy, design and software engineering for SaaS platforms, web applications, mobile apps and business systems." },
    hero: { eyebrow: "Services", title: "Software shaped around the challenge.", description: "From first product decisions to long-term evolution, we bring product thinking, design and engineering together around the result your business needs." },
    capabilities: { eyebrow: "Capabilities", titleLine1: "From product idea", titleLine2: "to working system.", description: "Choose a focused capability or bring us a challenge that crosses several. We shape the right team and approach around the work." },
    items: [
        { slug: "saas-platforms", title: "SaaS Platforms", shortTitle: "SaaS", description: "Scalable multi-user platforms, dashboards, subscription systems and cloud applications.", detail: "We turn a product vision into a secure, maintainable SaaS foundation—covering the experience, architecture and operational detail needed to grow with confidence.", deliverables: ["Product strategy", "Multi-tenant architecture", "Subscriptions and billing", "Admin and analytics"] },
        { slug: "web-applications", title: "Web Applications", shortTitle: "Web", description: "Complex browser-based products and operational systems made clear, fast and reliable.", detail: "From customer portals to data-rich operational tools, we create web applications around the real work people need to accomplish every day.", deliverables: ["UX and prototyping", "Frontend engineering", "API development", "Quality assurance"] },
        { slug: "mobile-applications", title: "Mobile Applications", shortTitle: "Mobile", description: "Native-feeling mobile experiences designed for the way your customers actually move.", detail: "We design and engineer focused mobile products that feel at home on every device and stay connected to the systems behind your business.", deliverables: ["Mobile product design", "Cross-platform development", "Backend integration", "Store readiness"] },
        { slug: "business-systems", title: "Business Systems", shortTitle: "Systems", description: "Internal tools, portals, workflow systems and automation built around your operation.", detail: "We replace fragmented spreadsheets and repetitive processes with tools that make work visible, consistent and easier to improve.", deliverables: ["Process discovery", "Internal portals", "Workflow automation", "System integrations"] },
        { slug: "ai-automation", title: "AI & Automation", shortTitle: "AI", description: "Practical AI-enabled workflows, integrations and intelligent automation with clear value.", detail: "We find the places where intelligent automation removes friction, then build governed systems that keep people in control.", deliverables: ["Opportunity mapping", "AI workflow design", "Model integration", "Evaluation and monitoring"] },
        { slug: "modernisation", title: "Modernisation", shortTitle: "Modernise", description: "Rebuilding outdated applications and architectures for the next stage of growth.", detail: "We help teams move beyond brittle legacy systems through a measured plan that protects business continuity while improving the foundation.", deliverables: ["Technical audit", "Modernisation roadmap", "Incremental rebuild", "Cloud migration"] },
    ],
    engagement: { eyebrow: "Ways to work together", titleLine1: "The right shape", titleLine2: "for the work.", description: "Clear expectations, direct communication and a delivery model suited to where your product is now.", items: [{ title: "Product foundation", description: "Define the opportunity, reduce uncertainty and leave with a validated direction, architecture and delivery plan." }, { title: "End-to-end build", description: "A focused product team takes your software from discovery through design, engineering and launch." }, { title: "Continuous evolution", description: "Long-term product and engineering support for improvements, new capabilities and responsible scaling." }] },
    detail: { eyebrow: "Service", title: "Built for the job it needs to do—and the future it needs to support.", teamTitle: "One team across product and technology.", teamParagraph1: "We start with the decision the software needs to improve, then work outward into the experience, data, integrations and technical foundation.", teamParagraph2: "You get a clear delivery path, visible trade-offs and maintainable work that can be understood by the team who will own it next." },
} as const;
