export const services = {
    meta: { title: "Leistungen", description: "Produktstrategie, Design und Softwareentwicklung für SaaS-Plattformen, Webanwendungen, mobile Apps und Geschäftssysteme." },
    hero: { eyebrow: "Leistungen", title: "Software, geformt durch die Herausforderung.", description: "Von den ersten Produktentscheidungen bis zur langfristigen Weiterentwicklung verbinden wir Produktdenken, Design und Engineering rund um das Ergebnis, das Ihr Unternehmen braucht." },
    capabilities: { eyebrow: "Kompetenzen", titleLine1: "Von der Produktidee", titleLine2: "zum funktionierenden System.", description: "Wählen Sie eine gezielte Kompetenz oder bringen Sie uns eine Herausforderung, die mehrere Bereiche umfasst. Wir formen das passende Team und Vorgehen." },
    items: [
        { slug: "saas-platforms", title: "SaaS-Plattformen", shortTitle: "SaaS", description: "Skalierbare Mehrbenutzer-Plattformen, Dashboards, Abonnementsysteme und Cloud-Anwendungen.", detail: "Wir verwandeln eine Produktvision in ein sicheres, wartbares SaaS-Fundament — von der Nutzererfahrung über die Architektur bis zu den operativen Details für zuverlässiges Wachstum.", deliverables: ["Produktstrategie", "Mandantenfähige Architektur", "Abonnements und Abrechnung", "Administration und Analysen"] },
        { slug: "web-applications", title: "Webanwendungen", shortTitle: "Web", description: "Komplexe browserbasierte Produkte und operative Systeme — klar, schnell und zuverlässig.", detail: "Von Kundenportalen bis zu datenreichen operativen Werkzeugen entwickeln wir Webanwendungen rund um die tatsächliche tägliche Arbeit der Menschen.", deliverables: ["UX und Prototyping", "Frontend Engineering", "API-Entwicklung", "Qualitätssicherung"] },
        { slug: "mobile-applications", title: "Mobile Anwendungen", shortTitle: "Mobile", description: "Native wirkende mobile Erlebnisse für die Art, wie Ihre Kunden unterwegs sind.", detail: "Wir gestalten und entwickeln fokussierte mobile Produkte, die sich auf jedem Gerät natürlich anfühlen und mit den Systemen hinter Ihrem Unternehmen verbunden bleiben.", deliverables: ["Mobiles Produktdesign", "Plattformübergreifende Entwicklung", "Backend-Integration", "Store-Vorbereitung"] },
        { slug: "business-systems", title: "Geschäftssysteme", shortTitle: "Systeme", description: "Interne Werkzeuge, Portale, Workflows und Automatisierung rund um Ihren Betrieb.", detail: "Wir ersetzen fragmentierte Tabellen und wiederkehrende Prozesse durch Werkzeuge, die Arbeit sichtbar, konsistent und leichter verbesserbar machen.", deliverables: ["Prozessanalyse", "Interne Portale", "Workflow-Automatisierung", "Systemintegrationen"] },
        { slug: "ai-automation", title: "KI & Automatisierung", shortTitle: "KI", description: "Praktische KI-gestützte Workflows, Integrationen und intelligente Automatisierung mit klarem Nutzen.", detail: "Wir finden die Stellen, an denen intelligente Automatisierung Reibung beseitigt, und bauen kontrollierte Systeme, in denen Menschen die Kontrolle behalten.", deliverables: ["Chancenanalyse", "KI-Workflow-Design", "Modellintegration", "Bewertung und Monitoring"] },
        { slug: "modernisation", title: "Modernisierung", shortTitle: "Modernisieren", description: "Erneuerung veralteter Anwendungen und Architekturen für die nächste Wachstumsphase.", detail: "Wir helfen Teams, fragile Altsysteme mit einem schrittweisen Plan zu überwinden, der den laufenden Betrieb schützt und das Fundament verbessert.", deliverables: ["Technisches Audit", "Modernisierungsplan", "Schrittweiser Neuaufbau", "Cloud-Migration"] },
    ],
    engagement: { eyebrow: "Formen der Zusammenarbeit", titleLine1: "Das richtige Modell", titleLine2: "für die Aufgabe.", description: "Klare Erwartungen, direkte Kommunikation und ein Liefermodell, das zur aktuellen Phase Ihres Produkts passt.", items: [{ title: "Produktfundament", description: "Definieren Sie die Chance, reduzieren Sie Unsicherheit und erhalten Sie eine validierte Richtung, Architektur und einen Lieferplan." }, { title: "End-to-End-Entwicklung", description: "Ein fokussiertes Produktteam führt Ihre Software von Discovery über Design und Engineering bis zum Launch." }, { title: "Kontinuierliche Entwicklung", description: "Langfristige Produkt- und Engineering-Unterstützung für Verbesserungen, neue Fähigkeiten und verantwortungsvolle Skalierung." }] },
    detail: { eyebrow: "Leistung", title: "Gebaut für die Aufgabe von heute — und die Zukunft, die es tragen soll.", teamTitle: "Ein Team für Produkt und Technologie.", teamParagraph1: "Wir beginnen mit der Entscheidung, die die Software verbessern soll, und arbeiten uns von dort zur Erfahrung, den Daten, Integrationen und dem technischen Fundament vor.", teamParagraph2: "Sie erhalten einen klaren Lieferweg, sichtbare Abwägungen und wartbare Arbeit, die das Team, das sie später übernimmt, verstehen kann." },
} as const;
